# Generated by Django 4.2.5 on 2023-09-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.ImageField(upload_to='image/content/')),
                ('style_image', models.ImageField(upload_to='image/style/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_image', models.ImageField(upload_to='generated_images/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='styletransferapp.userimage')),
            ],
        ),
    ]
