# Generated by Django 3.2.15 on 2023-09-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styletransferapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='content_selected_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='style_selected_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='content_image',
            field=models.ImageField(null=True, upload_to='image/content/'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='style_image',
            field=models.ImageField(null=True, upload_to='image/style/'),
        ),
    ]
